---
title: "Week 3"
author: "Tomás"
date: "19 de noviembre de 2019"
output: word_document
---

# Subsetting

```{r subsetting}
library(plyr)
set.seed(123)
x <- data.frame('var1' = sample(1:5),"var2" = sample(6:10), "var3" = sample(11:15))
x <- x[sample(1:5),] ; x$var2[c(1,3)] = NA
x[,1] # Primera columna del dataframe
x[,"var1"] # Columna var1 del dataframe
x[1:2,"var2"]#Columna var 2 y filas 1:2
x[(x$var1 <= 3 & x$var3 > 11),] # Busco filas que tengan var 1 mayor/igual que 3 y var 3 menor que 11
x[(x$var1 <= 3 | x$var3 > 15),] # Busco filas que var 1 sea mayor o igual a 3 o que var3 sea mayor que 15
x[which(x$var2 >8),] #La funcion which entrega los indices donde se comple esa condicion sin contar los NA
x[x$var2 >8,] # Sin la funcion which considera los NA
sort(x$var1) # Ordena la columna de menor a mayor
sort(x$var1, decreasing = TRUE)
sort(x$var2, na.last = TRUE)
x[order(x$var1),] #Me ordena el dataframe en funcion de la variable 1
x[order(x$var1,x$var3),] # Si existe empate en la variable 1, se orden por la variable 3
arrange(x,var1) # Mismo caso que order, pero mas compracto
arrange(x,desc(var1)) # Decreciente
x$var4 <- rnorm(5) # Añadir columna nueva
y <- cbind(x, "var5" = rnorm(5)) # Lo mismo pero debo crear otro dataframe, rbind agrega filas
```

#Summarazing data

```{r summarazing data}
data <- read.csv("Restaurants.csv")
head(data,3) # Visualizar las 3 primeras lineas
tail(data,3) # Visualizar las 3 ultimas lineas
summary(data) # Resumen de la data
str(data) #Entrega la clase de las variables y algunas caracteristicas del df
quantile(data$councilDistrict, na.rm = TRUE) # Me entrega los quantiles
table(data$zipCode, useNA = "ifany") # Entrega una tabla con las frecuencias de las observaciones (useNA = "ifany", entrega una columna extra si encuentra observaciones NA)
table(data$councilDistrict,data$zipCode) # Entrega una tabla de dos dimensiones con dos variables
sum(is.na(data$councilDistrict)) # Verifica si existen NA y los suma, en este caso no existe (Si hay NA is.na entrega un TRUE, TRUE se interpreta como 1)
any(is.na(data$councilDistrict)) # Pregunta si existe algun dato NA, any verifica si existe algun TRUE
all(data$zipCode > 0) #Verifica que todas las observaciones de esa variables son mayores que 0, si alguna es menor que 0 entrega FALSE
colSums(is.na(data)) # Suma por cada columna la cantidad de NA (se puede hacer por filas tambien "rowSums)
table(data$zipCode %in% c("21212","21213")) #Permite encontrar cuantas observaciones son parte de esos dos strings
data[data$zipCode %in% c("21212","21213"),] #Con esto puedo crear un subset que contiene solo las filas que pertenencen al character
data("UCBAdmissions")
df <- as.data.frame(UCBAdmissions)
summary(df)
xtabs(Freq ~ Gender + Admit , data = df) # Crea una tabla cruzada con el centro "Freq" y de variables Gender y Admit
data("warpbreaks")
df1 <- as.data.frame(warpbreaks)
warpbreaks$replicate <- rep(1:9, len = 54)
xt <- xtabs(breaks ~ . , data =  warpbreaks) # Le entrego todas las variables me hace todas las tablas posibles
ftable(xt) #Encuentro un resumen de lo anterior
```

#Creating New Variables

```{r Creating New Variables}
data <- read.csv("Restaurants.csv")
s1 <- seq(1,10,by=2) ; s1 #Crea una secuencia de numeros del 1 al 10 cada dos
s2 <- seq(1,10, lenght = 3); s2 #Crea una secuencia de exactamente 3 numeros
x <- c(1,3,8,25,100); seq(along = x) #Crea una secuencia empezando por 1 del mismo largo que el vector
data$nearme <- data$neighborhood %in% c("Roland Park", "Homeland") #Con esto he creadro una variable que indica cuales restaurantes esta cerca mio segun los vecindarios que he espicificado
table(data$nearme)
data$zipwrong <- ifelse(data$zipCode < 0,TRUE,FALSE) # Crea una nueva variable si el zip code es menor que 0
table(data$zipwrong,data$zipCode<0)
data$zipgroups <- cut(data$zipCode,breaks = quantile(data$zipCode)) #Divide en los cuartiles los zipcode
table(data$zipgroups)
table(data$zipgroups,data$zipCode)
library(Hmisc)
data$zipgroups <- cut2(data$zipCode,g=4) # Divide los zip code en 4 grupos
table(data$zipgroups)
data$zcf <- factor(data$zipCode) ; data$zcf[1:10] # Convierte una variable que es integer en un factor, asi se pueden realizar regresiones lineales por ejemplo donde no necesariamente "mas zipcode" implica algo mejor
class(data$zcf)
library(plyr)
data2 <- mutate(data, zipGroups=cut2(zipCode,g=4))
```

#Reshaping Data

```{r Reshaping Data}
library(reshape2)
library(datasets)
data("mtcars")
head(mtcars)
mtcars$carname <- rownames(mtcars)
carMelt <- melt(mtcars, id=c("carname","gear","cyl"), measure.cars = c("mpg","hp"))
cylData <- dcast(carMelt, cyl ~ variable) ; cylData
#ddply() # Se puede splitear un dataframe, mandarle una funcion y despues lo deja como un dataframe.
```

#Dplyr

```{r  Dplyr}
library(dplyr)
chicago <- readRDS("chicago.rds")
head(select(chicago, city:dptp)) # Select me permite utilizar los nombres de las variables y no sus indices
head(select(chicago, -(city:dptp))) # Puedo seleccionar todas menos la que le indico -()
chic.f <- filter(chicago, chicago$pm25tmean2 > 30) # Filtrar con una condicion
chic.f <- filter(chicago, chicago$pm25tmean2 > 30 & chicago$tmpd > 80) # Mas de una condicion
chicago <- arrange(chicago,date) # Puedo organizar por alguna variable
chicago <- rename(chicago, pm25 = pm25tmean2, dewpoint = dptp) #Renombra una variable
chicago <- mutate(chicago, pm25detrend = pm25-mean(pm25, na.rm = TRUE)) #Permite crear otra variable con informacion de alguna existente
chicago <- mutate(chicago, tempcat = factor(1*(tmpd >80), labels = c("cold","hot")))
hot_cold <- group_by(chicago,tempcat)
summarize(hot_cold, pm25 = mean(pm25, na.rm = TRUE), o3 = max(o3tmean2), n02 = mean(no2tmean2))
```